# Generated by Django 4.0 on 2022-05-10 12:28

from django.db import migrations, models
import filmapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное имя и фамилия режиссёра', max_length=100, verbose_name='Имя и фамилия')),
                ('year', models.IntegerField(help_text='Год рождения режиссёра', null=True, validators=[filmapp.models.validate_positive], verbose_name='Год рождения')),
            ],
            options={
                'verbose_name': 'Режиссёр',
                'verbose_name_plural': 'Режиссёры',
                'ordering': ('name', '-year'),
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название на русском языке', max_length=100, verbose_name='Название')),
                ('original_name', models.CharField(blank=True, help_text='Оригинальное название, данное при создании', max_length=100, null=True, verbose_name='Оригинальное название')),
                ('year', models.IntegerField(help_text='Год создания фильма', null=True, validators=[filmapp.models.validate_positive], verbose_name='Год')),
                ('directors', models.ManyToManyField(to='filmapp.Director')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ('name', '-year', 'original_name'),
            },
        ),
    ]
