# Generated by Django 4.0 on 2022-05-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='cover',
            field=models.ImageField(help_text='Обложка фильма. Может быть как на языке оригинала, так и русская адаптированная', null=True, upload_to='films_cover/', verbose_name='Обложка фильма'),
        ),
    ]
