# Generated by Django 4.0 on 2022-04-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0002_director_filmdirector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='date',
            new_name='year',
        ),
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(to='filmapp.Director'),
        ),
        migrations.DeleteModel(
            name='FilmDirector',
        ),
    ]
