# Generated by Django 4.0 on 2022-04-24 18:39

from django.db import migrations, models
import filmapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0003_rename_date_film_year_film_directors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='original_name',
            field=models.CharField(blank=True, help_text='Оригинальное название', max_length=100, null=True, verbose_name='Оригинальное название'),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(help_text='Полное имя и фамилия режиссёра', max_length=100, verbose_name='Имя и фамилия'),
        ),
        migrations.AlterField(
            model_name='director',
            name='year',
            field=models.IntegerField(help_text='Год рождения режиссёра', null=True, validators=[filmapp.models.validate_positive], verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(help_text='Название на русском языке', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(help_text='Год создания фильма', null=True, validators=[filmapp.models.validate_positive], verbose_name='Год'),
        ),
    ]
