# Generated by Django 4.0 on 2022-04-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0004_film_original_name_alter_director_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ('name', '-year'), 'verbose_name': 'Режиссёр', 'verbose_name_plural': 'Режиссёры'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('name', '-year', 'original_name'), 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterField(
            model_name='film',
            name='original_name',
            field=models.CharField(blank=True, help_text='Оригинальное название, данное при создании', max_length=100, null=True, verbose_name='Оригинальное название'),
        ),
    ]
